### ISSUE TITLE
Confounding variables affecting our main covariate?

### ISSUE THREAD

**Issue by Pall-v** [UBC-MDS/Self-perceived-Difficulty-of-DSCI-512-Analysis#20]
@tung_patrick, @mru4913:

Hey, the new proposal draft looks good!    

Question: is there a reason that we are talking about our confounding variables affecting our main covariate?  For example: “mathematical abilities may affect their level of programming experience”, and “if a MDS student has friends or family who work for IT companies, they are more likely to be affected and tend to have programming experience before the program”.  

I think that for confounding variables, we would only be interested in their effect on our dependent variable (difficulty) that is not already captured by our main covariate (programming experience).  Does that make sense, or am I not understanding things correctly?

**Comment by tungpatrick** [comment]
I think the whole point of confounding variables is that is affects both the dependent and independent variables. At least.. that's my understanding haha.
![](https://explorable.com/sites/default/files/documents/third-variable.png)

**Comment by mru4913** [comment]
Very good question!! Correct me if I am wrong.

For [condounding variables](https://en.wikipedia.org/wiki/Confounding), it is a common cause of both independent variable and dependent variable.

The note I took from lecture 2 slide.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/31579276/55251539-13664500-520e-11e9-8372-4178a3eb7778.png">

**Comment by Pall-v** [comment]
Thanks, I overlooked that.  I'll make sure the proposal aligns with this.
