### ISSUE TITLE
Created Survey

### ISSUE THREAD

**Issue by tungpatrick** [UBC-MDS/Self-perceived-Difficulty-of-DSCI-512-Analysis#26]
I went ahead and created the survey:
https://ubc.ca1.qualtrics.com/jfe/form/SV_abNhXIL4B4pM6sl

One question I have for you guys is... should we tick this box? "Anonymize..."
![Screen Shot 2019-04-02 at 4 34 14 PM](https://user-images.githubusercontent.com/43163296/55442928-7d138580-5565-11e9-9d0c-9e6c7644bc33.png)

**Comment by mru4913** [comment]
Great Job! Patrick.

1. Since it states "not recommended", I assume that we should not do select the box.
2. Patrick, is it possible to add a cover letter that includes "the sentence: “By completing the questionnaire, you are consenting to participate in this resear...."?

**Comment by tungpatrick** [comment]
@mru4913 I FIXED IT!

https://ubc.ca1.qualtrics.com/jfe/form/SV_abNhXIL4B4pM6sl
